# Generated by Django 6.0.6 on 2026-06-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_truckstop_id", models.CharField(blank=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("state", models.CharField(blank=True, max_length=64)),
                ("rack_id", models.CharField(blank=True, max_length=64)),
                (
                    "average_retail_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "highest_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("city_lat", models.FloatField(blank=True, null=True)),
                ("city_lon", models.FloatField(blank=True, null=True)),
                ("geocoded_lat", models.FloatField(blank=True, null=True)),
                ("geocoded_lon", models.FloatField(blank=True, null=True)),
                ("matched_address", models.CharField(blank=True, max_length=512)),
                ("geocode_status", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
