# Generated by Django 6.0.6 on 2026-06-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="opis_truckstop_id",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
